server:
  port: 8089

spring:
  redis:
    cluster:
      #集群节点
      nodes: 127.0.0.1:8001,127.0.0.1:8002,127.0.0.1:8003,127.0.0.1:8004,127.0.0.1:8005,127.0.0.1:8006
      #最大重试次数
      max-redirects: 5
    password: zhuge
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/explain?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password: root
redisson:
  address: redis://127.0.0.1:8003
  password: zhuge
#mybatis:配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.bean    # 所有pojo别名类所在包


